version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "cloudbasedproject-1-container"
          ContainerPort: 2021
        PlatformVersion: "1.4.0"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - "subnet-xxxxx"  # Replace with your private subnet IDs
              - "subnet-yyyyy"
            SecurityGroups:
              - "sg-zzzzz"     # Replace with your ECS security group ID
            AssignPublicIp: "DISABLED"
Hooks:
  - BeforeInstall: 
      - Location: "scripts/stop_application.sh"
        Timeout: 300
        Runas: "root"
  - AfterInstall:
      - Location: "scripts/start_application.sh"
        Timeout: 300
        Runas: "root"
  - ApplicationStart:
      - Location: "scripts/validate_service.sh"
        Timeout: 300
        Runas: "root"