version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "cloudbasedproject-1-container"
          ContainerPort: 2021
        PlatformVersion: "1.4.0"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - "subnet-04ad6a00dd70364a7"  
              - "subnet-09a64709cf4a7c48b"
            SecurityGroups:
              - "sg-0e51aa334c109d3ea"     
            AssignPublicIp: "DISABLED"
Hooks:
  - BeforeInstall: 
      - Location: "scripts/stop_application.sh"
        Timeout: 300
        Runas: "root"
  - AfterInstall:
      - Location: "scripts/start_application.sh"
        Timeout: 300
        Runas: "root"
  - ApplicationStart:
      - Location: "scripts/validate_service.sh"
        Timeout: 300
        Runas: "root"